engines:
  duplication:
    exclude_paths:
      - "message/*"
      - "internal/server/*"
      - "**/*_test.go"
      - "**/*_mock.go"
      - "**/*_gen.go"
exclude_paths:
  - "message/**"
  - "internal/server/*"
  - "**/*_test.go"
  - "**/*_mock.go"
  - "**/*_gen.go"